import 'dart:io';
import 'package:mason/mason.dart';

// Adds one new page/sub-flow to an EXISTING feature module — e.g. adding
// "change_password" alongside auth's existing "signin"/"signup". The
// page's own files (view, viewmodel, a usecase stub) are generated by
// Mason itself from __brick__/lib/features/{{featureFileName}}/..., using
// the featureFileName/featureClassName/fileName/className/camelName vars
// computed in pre_gen.dart. This hook only handles wiring the freshly
// generated page into files that already existed before this run —
// route_names.dart, route_paths.dart, app_router.dart, and
// injection_container.dart.
//
// Unlike create_feature, this never registers a new datasource/repository
// — it assumes `I{{featureClassName}}Repository` is already registered by
// the feature's own dependency function, and the new usecase just depends
// on that existing singleton via `sl()`.
//
// All insertions below reuse the same `// GENERATED_..._START` /
// `_END` marker anchors create_feature relies on, for the same reason:
// fail loudly with an actionable message if a marker is missing, rather
// than guessing via brace-counting or corrupting the file.
Future<void> run(HookContext context) async {
  final logger = context.logger;

  final featureFileName = context.vars['featureFileName'] as String;
  final featureClassName = context.vars['featureClassName'] as String;
  final fileName = context.vars['fileName'] as String;
  final className = context.vars['className'] as String;
  final camelName = context.vars['camelName'] as String;

  final libDir = Directory('${Directory.current.path}/lib');
  final touchedFiles = <File>[];

  touchedFiles.addAll(
    _updateRoutes(
      libDir,
      featureFileName,
      className,
      fileName,
      camelName,
      logger,
    ),
  );
  touchedFiles.addAll(
    _updateDependencyInjection(
      libDir,
      featureFileName,
      featureClassName,
      className,
      fileName,
      camelName,
      logger,
    ),
  );
  touchedFiles.addAll(
    _updateFeatureExports(libDir, featureFileName, fileName, logger),
  );

  final pageDir = Directory(
    '${libDir.path}/features/$featureFileName/presentation/$fileName',
  );
  final usecaseFile = File(
    '${libDir.path}/features/$featureFileName/domain/usecases/${fileName}_usecase.dart',
  );
  await _formatPaths([
    ...touchedFiles.map((f) => f.path),
    if (pageDir.existsSync()) pageDir.path,
    if (usecaseFile.existsSync()) usecaseFile.path,
  ], logger);

  logger.success('\n✅ $className page wired into routes and DI!');
  logger.info(
    '''
💡 ${className}Usecase is a stub — it throws UnimplementedError until you:
   1. Add a `$camelName(...)` method to I${featureClassName}Repository
      (domain/repositories/${featureFileName}_repository.dart) and its impl.
   2. Replace the `dynamic`/`NoParams` types in
      domain/usecases/${fileName}_usecase.dart with the real request/
      response types this page needs, and call the new repository method.''',
  );
}

// ------------------------------------------------------------------
// 🧩 UPDATE ROUTES AUTOMATICALLY
// ------------------------------------------------------------------
List<File> _updateRoutes(
  Directory libDir,
  String featureFileName,
  String className,
  String fileName,
  String camelName,
  Logger logger,
) {
  final routesDir = Directory('${libDir.path}/routes');
  final touched = <File>[];

  // ✅ 1. Update route_names.dart — the constant *identifier* is
  // camelCase (`camelName`) even though the route's own name/path
  // *value* stays snake_case (`fileName`), so multi-word page names like
  // "change_password" don't trip the `constant_identifier_names` lint
  // (fatal under this project's `flutter analyze --fatal-infos` CI job).
  final namesFile = File('${routesDir.path}/route_names.dart');
  if (namesFile.existsSync()) {
    String content = namesFile.readAsStringSync();

    if (!content.contains('static const String $camelName')) {
      final updated = _insertBeforeMarker(
        content,
        'GENERATED_ROUTE_NAMES',
        '  static const String $camelName = "$fileName";\n',
      );
      if (updated != null) {
        namesFile.writeAsStringSync(updated);
        touched.add(namesFile);
        logger.success('🧭 Updated: lib/routes/route_names.dart');
      } else {
        logger.err(
          '❌ lib/routes/route_names.dart is missing the '
          '"// GENERATED_ROUTE_NAMES_END" marker — add it inside the '
          'RouteNames class and re-run.',
        );
      }
    } else {
      logger.warn('⚠️  Route name "$fileName" already exists');
    }
  }

  // ✅ 2. Update route_paths.dart
  final pathsFile = File('${routesDir.path}/route_paths.dart');
  if (pathsFile.existsSync()) {
    String content = pathsFile.readAsStringSync();

    if (!content.contains('static const String $camelName')) {
      final updated = _insertBeforeMarker(
        content,
        'GENERATED_ROUTE_PATHS',
        '  static const String $camelName = "/$fileName";\n',
      );
      if (updated != null) {
        pathsFile.writeAsStringSync(updated);
        touched.add(pathsFile);
        logger.success('🧭 Updated: lib/routes/route_paths.dart');
      } else {
        logger.err(
          '❌ lib/routes/route_paths.dart is missing the '
          '"// GENERATED_ROUTE_PATHS_END" marker — add it inside the '
          'RoutePaths class and re-run.',
        );
      }
    } else {
      logger.warn('⚠️  Route path "/$fileName" already exists');
    }
  }

  // ✅ 3. Update app_router.dart — imports the feature's barrel export
  // (same one create_feature wires up for the feature's existing pages),
  // since _updateFeatureExports() below adds the new page to that barrel
  // rather than leaving it reachable only via a direct file import.
  final routerFile = File('${routesDir.path}/app_router.dart');
  if (routerFile.existsSync()) {
    String content = routerFile.readAsStringSync();

    if (!content.contains('${className}Page()')) {
      final withImport = _insertImportIfMissing(
        content,
        "import '../features/$featureFileName/${featureFileName}_exports.dart';",
      );
      if (withImport == null) {
        logger.err(
          '❌ lib/routes/app_router.dart is missing the '
          '"// GENERATED_IMPORTS_END" marker — add it below the existing '
          'imports and re-run.',
        );
      } else {
        content = withImport;

        final newRoute =
            '''
      GoRoute(
        path: RoutePaths.$camelName,
        name: RouteNames.$camelName,
        builder: (context, state) => const ${className}Page(),
      ),''';

        final updated = _insertBeforeMarker(
          content,
          'GENERATED_ROUTES',
          '$newRoute\n',
        );
        if (updated != null) {
          routerFile.writeAsStringSync(updated);
          touched.add(routerFile);
          logger.success('🧭 Updated: lib/routes/app_router.dart');
        } else {
          logger.err(
            '❌ lib/routes/app_router.dart is missing the '
            '"// GENERATED_ROUTES_END" marker — add it right before the '
            'closing "]," of AppRoutes.router\'s routes list and re-run.',
          );
        }
      }
    } else {
      logger.warn('⚠️  Route for ${className}Page already exists');
    }
  }

  return touched;
}

// ------------------------------------------------------------------
// 🧩 UPDATE DEPENDENCY INJECTION AUTOMATICALLY
// ------------------------------------------------------------------
List<File> _updateDependencyInjection(
  Directory libDir,
  String featureFileName,
  String featureClassName,
  String className,
  String fileName,
  String camelName,
  Logger logger,
) {
  final diFile = File('${libDir.path}/core/di/injection_container.dart');

  if (!diFile.existsSync()) {
    logger.err('❌ injection_container.dart not found');
    return const [];
  }

  String content = diFile.readAsStringSync();

  if (content.contains('${camelName}Dependencies')) {
    logger.warn('⚠️  Dependencies for $fileName already exist');
    return const [];
  }

  // Make sure the new usecase/viewmodel types are importable. Imported via
  // the feature's barrel export (already imported here for the feature's
  // existing pages), since _updateFeatureExports() below adds the new
  // page's exports to that same barrel.
  final withImports = _insertImportIfMissing(
    content,
    "import '../../features/$featureFileName/${featureFileName}_exports.dart';",
  );
  if (withImports == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_IMPORTS_END" marker — add it below the existing '
      'imports and re-run.',
    );
    return const [];
  }
  content = withImports;

  // ✅ 1. Add the dependency function, right before GENERATED_DEPENDENCIES_END
  final newDependencyFunction =
      '''
/// $className page dependencies (part of the $featureClassName feature —
/// reuses its existing I${featureClassName}Repository registration).
Future<void> ${camelName}Dependencies() async {
  // UseCase
  sl.registerLazySingleton<${className}Usecase>(
    () => ${className}Usecase(repository: sl()),
  );

  // ViewModel
  sl.registerFactory<${className}ViewModel>(
    () => ${className}ViewModel(${camelName}Usecase: sl()),
  );
}

''';

  final withDependencyFunction = _insertBeforeMarker(
    content,
    'GENERATED_DEPENDENCIES',
    newDependencyFunction,
  );
  if (withDependencyFunction == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_DEPENDENCIES_END" marker — add it at the end of the '
      'file and re-run.',
    );
    return const [];
  }
  content = withDependencyFunction;

  // ✅ 2. Add the function call, right before GENERATED_SETUP_CALLS_END
  final withSetupCall = _insertBeforeMarker(
    content,
    'GENERATED_SETUP_CALLS',
    '  await ${camelName}Dependencies();\n',
  );
  if (withSetupCall == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_SETUP_CALLS_END" marker — add it at the end of '
      'setupLocator() and re-run.',
    );
    return const [];
  }
  content = withSetupCall;

  diFile.writeAsStringSync(content);
  logger.success('🧱 Updated: lib/core/di/injection_container.dart');
  return [diFile];
}

// ------------------------------------------------------------------
// 🧩 UPDATE FEATURE BARREL EXPORT AUTOMATICALLY
// ------------------------------------------------------------------
/// Appends the new page's view/viewmodel/usecase exports to
/// `<feature>_exports.dart`. That file has no `GENERATED_..._END` marker
/// (unlike routes/DI) because it's just a flat list of `export` statements
/// with no surrounding class/braces — appending to the end is exactly as
/// safe as inserting at a marker would be, so no marker is needed.
List<File> _updateFeatureExports(
  Directory libDir,
  String featureFileName,
  String fileName,
  Logger logger,
) {
  final exportsFile = File(
    '${libDir.path}/features/$featureFileName/${featureFileName}_exports.dart',
  );
  if (!exportsFile.existsSync()) {
    logger.warn(
      '⚠️  ${featureFileName}_exports.dart not found — skipped updating the '
      'barrel export.',
    );
    return const [];
  }

  final newExports = [
    "export 'presentation/$fileName/views/${fileName}_page.dart';",
    "export 'presentation/$fileName/viewmodels/${fileName}_viewmodel.dart';",
    "export 'domain/usecases/${fileName}_usecase.dart';",
  ];

  String content = exportsFile.readAsStringSync();
  final missing = newExports.where((line) => !content.contains(line));
  if (missing.isEmpty) {
    logger.warn('⚠️  ${featureFileName}_exports.dart already up to date');
    return const [];
  }

  final buffer = StringBuffer(content.trimRight());
  for (final line in missing) {
    buffer.write('\n$line');
  }
  buffer.write('\n');
  exportsFile.writeAsStringSync(buffer.toString());
  logger.success('🧱 Updated: ${featureFileName}_exports.dart');
  return [exportsFile];
}

// ------------------------------------------------------------------
// 🧩 HELPER FUNCTIONS
// ------------------------------------------------------------------

/// Inserts [insertion] immediately before the line containing
/// `// {marker}_END` in [content]. Returns `null` (instead of guessing via
/// brace-counting or substring search) if that marker isn't present, so
/// callers can fail loudly with instructions rather than silently
/// corrupting a file whose shape doesn't match what was assumed.
String? _insertBeforeMarker(String content, String marker, String insertion) {
  final endMarkerLine = RegExp(
    '^[ \\t]*// ${RegExp.escape(marker)}_END[ \\t]*\$',
    multiLine: true,
  ).firstMatch(content);
  if (endMarkerLine == null) return null;

  final lineStart = content.lastIndexOf('\n', endMarkerLine.start) + 1;
  return content.substring(0, lineStart) +
      insertion +
      content.substring(lineStart);
}

/// Inserts [importLine] right before the `// GENERATED_IMPORTS_END` marker
/// in [content], unless it's already present. Returns `null` if that
/// marker isn't found.
String? _insertImportIfMissing(String content, String importLine) {
  if (content.contains(importLine)) return content;
  return _insertBeforeMarker(content, 'GENERATED_IMPORTS', '$importLine\n');
}

/// Runs `dart format` on every file/directory this hook touched or
/// generated, so brick-generated code doesn't drift from the project's
/// formatting standard over time.
Future<void> _formatPaths(List<String> paths, Logger logger) async {
  if (paths.isEmpty) return;

  final result = await Process.run('dart', [
    'format',
    ...paths,
  ], runInShell: true);

  if (result.exitCode == 0) {
    logger.success('🎨 Formatted generated/updated files');
  } else {
    logger.warn('⚠️  dart format failed: ${result.stderr}');
  }
}
