import 'dart:io';
import 'package:mason/mason.dart';

// Adds Firebase Authentication as a drop-in alternative to this template's
// REST-backed auth. The new Dart source files themselves (FirebaseAuthHelper,
// the exception mapper, FirebaseAuthRepositoryImpl) are generated by Mason
// from __brick__/lib/... — this hook only wires them into files that
// already existed before this run: pubspec.yaml, the Android Gradle files,
// lib/main.dart, lib/core/di/injection_container.dart, and this feature's
// own auth_exports.dart barrel.
//
// Deliberately does NOT register FirebaseAuthRepositoryImpl as the active
// IAuthRepository — that's a one-line, deliberate choice left to the
// developer (see the printed instructions at the end), so running this
// brick can never silently change an app's auth backend out from under it.
Future<void> run(HookContext context) async {
  final logger = context.logger;
  final projectRoot = Directory.current.path;
  final libDir = Directory('$projectRoot/lib');

  final touchedFiles = <File>[];

  final pubspecTouched = _updatePubspec(projectRoot, logger);
  if (pubspecTouched != null) touchedFiles.add(pubspecTouched);

  // Gradle/pubspec files aren't valid input for `dart format` below, so
  // they're applied directly and never added to touchedFiles.
  _updateAndroidGradle(projectRoot, logger);
  touchedFiles.addAll(_updateMain(libDir, logger));
  touchedFiles.addAll(_updateDependencyInjection(libDir, logger));
  touchedFiles.addAll(_updateAuthExports(libDir, logger));

  final firebaseCoreDir = Directory('${libDir.path}/core/networks/firebase');
  final firebaseAuthImplFile = File(
    '${libDir.path}/features/auth/data/repository_impl/firebase_auth_repository_impl.dart',
  );
  await _formatPaths([
    ...touchedFiles.where((f) => f.path.endsWith('.dart')).map((f) => f.path),
    if (firebaseCoreDir.existsSync()) firebaseCoreDir.path,
    if (firebaseAuthImplFile.existsSync()) firebaseAuthImplFile.path,
  ], logger);

  logger.success('\n✅ Firebase Auth infrastructure added!');
  logger.info(
    '''
💡 Next steps:
   1. Run `flutterfire configure` (or manually add
      android/app/google-services.json and
      ios/Runner/GoogleService-Info.plist from your Firebase console
      project). The Android Gradle plugin only activates once
      google-services.json is present, so the app still builds/runs fine
      before you do this.
   2. In the Firebase console, enable the Email/Password sign-in provider
      under Authentication -> Sign-in method.
   3. Run `flutter pub get` to fetch firebase_core/firebase_auth.
   4. Auth still runs on the REST-backed AuthRepositoryImpl by default. To
      switch it to Firebase, edit authDependencies() in
      lib/core/di/injection_container.dart and change:
         AuthRepositoryImpl(dataSource: sl())
      to:
         FirebaseAuthRepositoryImpl(firebaseAuthHelper: sl())
      Nothing else (usecases, viewmodels, views, SessionController) needs
      to change — both implementations satisfy the same IAuthRepository
      contract.''',
  );
}

// ------------------------------------------------------------------
// 🧩 UPDATE pubspec.yaml
// ------------------------------------------------------------------
File? _updatePubspec(String projectRoot, Logger logger) {
  final pubspecFile = File('$projectRoot/pubspec.yaml');
  final crlf = _RawFile(pubspecFile);

  if (crlf.content.contains('firebase_core:')) {
    logger.warn('⚠️  pubspec.yaml already has firebase_core');
    return null;
  }

  const anchor = 'internet_connection_checker: ^3.0.1\n';
  if (!crlf.content.contains(anchor)) {
    logger.err(
      '❌ pubspec.yaml is missing the expected '
      '"internet_connection_checker: ^3.0.1" line — add firebase_core '
      'and firebase_auth to dependencies yourself.',
    );
    return null;
  }

  crlf.content = crlf.content.replaceFirst(
    anchor,
    '$anchor  firebase_core: ^3.8.0\n  firebase_auth: ^5.3.3\n',
  );
  crlf.save();
  logger.success('📦 Updated: pubspec.yaml');
  return pubspecFile;
}

// ------------------------------------------------------------------
// 🧩 UPDATE ANDROID GRADLE FILES
// ------------------------------------------------------------------
List<File> _updateAndroidGradle(String projectRoot, Logger logger) {
  final touched = <File>[];

  // ✅ 1. Declare the google-services plugin (with a resolvable version)
  // at the root, same as com.android.application/kotlin.android above it.
  // `apply false` here means "make it resolvable", not "apply it" — the
  // actual application is conditional, in app/build.gradle.kts below.
  final settingsFile = File('$projectRoot/android/settings.gradle.kts');
  if (settingsFile.existsSync()) {
    final crlf = _RawFile(settingsFile);
    if (crlf.content.contains('com.google.gms.google-services')) {
      logger.warn('⚠️  android/settings.gradle.kts already has google-services');
    } else {
      const anchor =
          '    id("org.jetbrains.kotlin.android") version "2.2.20" apply false\n';
      if (!crlf.content.contains(anchor)) {
        logger.err(
          '❌ android/settings.gradle.kts doesn\'t match the expected '
          'plugins block — add '
          '`id("com.google.gms.google-services") version "4.4.2" apply '
          'false` to it yourself.',
        );
      } else {
        crlf.content = crlf.content.replaceFirst(
          anchor,
          '$anchor'
          '    id("com.google.gms.google-services") version "4.4.2" apply false\n',
        );
        crlf.save();
        touched.add(settingsFile);
        logger.success('🧭 Updated: android/settings.gradle.kts');
      }
    }
  } else {
    logger.warn('⚠️  android/settings.gradle.kts not found — skipped');
  }

  // ✅ 2. Apply the plugin in the app module — but ONLY if
  // google-services.json actually exists, so a fresh clone (before
  // Firebase is configured) still builds instead of failing with
  // "File google-services.json is missing".
  final appGradleFile = File('$projectRoot/android/app/build.gradle.kts');
  if (appGradleFile.existsSync()) {
    final crlf = _RawFile(appGradleFile);
    if (crlf.content.contains('com.google.gms.google-services')) {
      logger.warn('⚠️  android/app/build.gradle.kts already has google-services');
    } else {
      const anchor =
          'plugins {\n'
          '    id("com.android.application")\n'
          '    id("kotlin-android")\n'
          '    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.\n'
          '    id("dev.flutter.flutter-gradle-plugin")\n'
          '}\n';
      if (!crlf.content.contains(anchor)) {
        logger.err(
          '❌ android/app/build.gradle.kts doesn\'t match the expected '
          'plugins block — apply the google-services plugin '
          '(conditionally on google-services.json existing) yourself.',
        );
      } else {
        const conditionalApply =
            '\n'
            '// Firebase (google-services.json) — applied only if that file exists,\n'
            '// so builds/CI keep working before Firebase is actually configured.\n'
            '// See the add_firebase brick\'s README for how to add this file.\n'
            'if (file("google-services.json").exists()) {\n'
            '    apply(plugin = "com.google.gms.google-services")\n'
            '}\n';
        crlf.content = crlf.content.replaceFirst(
          anchor,
          '$anchor$conditionalApply',
        );
        crlf.save();
        touched.add(appGradleFile);
        logger.success('🧭 Updated: android/app/build.gradle.kts');
      }
    }
  } else {
    logger.warn('⚠️  android/app/build.gradle.kts not found — skipped');
  }

  return touched;
}

// ------------------------------------------------------------------
// 🧩 UPDATE lib/main.dart
// ------------------------------------------------------------------
List<File> _updateMain(Directory libDir, Logger logger) {
  final mainFile = File('${libDir.path}/main.dart');
  if (!mainFile.existsSync()) {
    logger.err('❌ lib/main.dart not found');
    return const [];
  }

  final crlf = _RawFile(mainFile);
  if (crlf.content.contains('Firebase.initializeApp()')) {
    logger.warn('⚠️  lib/main.dart already calls Firebase.initializeApp()');
    return const [];
  }

  const importAnchor = "import 'package:provider/provider.dart';\n";
  const initAnchor = '      await setupLocator();\n';
  if (!crlf.content.contains(importAnchor) ||
      !crlf.content.contains(initAnchor)) {
    logger.err(
      '❌ lib/main.dart doesn\'t match the expected structure — add '
      '`import \'package:firebase_core/firebase_core.dart\';` and call '
      '`await Firebase.initializeApp();` before `await setupLocator();` '
      'yourself.',
    );
    return const [];
  }

  crlf.content = crlf.content.replaceFirst(
    importAnchor,
    "$importAnchor\nimport 'package:firebase_core/firebase_core.dart';",
  );
  crlf.content = crlf.content.replaceFirst(
    initAnchor,
    '      await Firebase.initializeApp();\n$initAnchor',
  );

  crlf.save();
  logger.success('🧭 Updated: lib/main.dart');
  return [mainFile];
}

// ------------------------------------------------------------------
// 🧩 UPDATE lib/core/di/injection_container.dart
// ------------------------------------------------------------------
List<File> _updateDependencyInjection(Directory libDir, Logger logger) {
  final diFile = File('${libDir.path}/core/di/injection_container.dart');
  if (!diFile.existsSync()) {
    logger.err('❌ injection_container.dart not found');
    return const [];
  }

  String content = diFile.readAsStringSync();
  if (content.contains('firebaseDependencies')) {
    logger.warn('⚠️  Firebase dependencies already registered');
    return const [];
  }

  final withAuthImport = _insertImportIfMissing(
    content,
    "import 'package:firebase_auth/firebase_auth.dart';",
  );
  if (withAuthImport == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_IMPORTS_END" marker — add it below the existing '
      'imports and re-run.',
    );
    return const [];
  }
  final withImports = _insertImportIfMissing(
    withAuthImport,
    "import '../networks/firebase/firebase_auth_helper.dart';",
  );
  if (withImports == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_IMPORTS_END" marker — add it below the existing '
      'imports and re-run.',
    );
    return const [];
  }
  content = withImports;

  const dependencyFunction =
      '''
/// Firebase Auth infrastructure — registered but NOT wired into
/// IAuthRepository by default (that stays on the REST-backed
/// AuthRepositoryImpl in authDependencies() above, so existing behavior
/// doesn't change under you). To switch auth over to Firebase, change the
/// IAuthRepository registration above from
/// `AuthRepositoryImpl(dataSource: sl())` to
/// `FirebaseAuthRepositoryImpl(firebaseAuthHelper: sl())` — everything
/// above the repository (usecases, viewmodels, views) stays unchanged.
Future<void> firebaseDependencies() async {
  sl.registerLazySingleton<FirebaseAuth>(() => FirebaseAuth.instance);
  sl.registerLazySingleton<FirebaseAuthHelper>(
    () => FirebaseAuthHelper(sl()),
  );
}

''';

  final withDependencyFunction = _insertBeforeMarker(
    content,
    'GENERATED_DEPENDENCIES',
    dependencyFunction,
  );
  if (withDependencyFunction == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_DEPENDENCIES_END" marker — add it at the end of the '
      'file and re-run.',
    );
    return const [];
  }
  content = withDependencyFunction;

  final withSetupCall = _insertBeforeMarker(
    content,
    'GENERATED_SETUP_CALLS',
    '  await firebaseDependencies();\n',
  );
  if (withSetupCall == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_SETUP_CALLS_END" marker — add it at the end of '
      'setupLocator() and re-run.',
    );
    return const [];
  }
  content = withSetupCall;

  diFile.writeAsStringSync(content);
  logger.success('🧱 Updated: lib/core/di/injection_container.dart');
  return [diFile];
}

// ------------------------------------------------------------------
// 🧩 UPDATE auth's barrel export
// ------------------------------------------------------------------
List<File> _updateAuthExports(Directory libDir, Logger logger) {
  final exportsFile = File('${libDir.path}/features/auth/auth_exports.dart');
  if (!exportsFile.existsSync()) {
    logger.warn(
      '⚠️  auth_exports.dart not found — skipped updating the barrel '
      'export.',
    );
    return const [];
  }

  const newExport =
      "export 'data/repository_impl/firebase_auth_repository_impl.dart';";
  String content = exportsFile.readAsStringSync();
  if (content.contains(newExport)) {
    logger.warn('⚠️  auth_exports.dart already up to date');
    return const [];
  }

  final buffer = StringBuffer(content.trimRight());
  buffer.write('\n$newExport\n');
  exportsFile.writeAsStringSync(buffer.toString());
  logger.success('🧱 Updated: auth_exports.dart');
  return [exportsFile];
}

/// Reads a file, normalizing CRLF to LF so plain string anchors (unlike
/// the marker-based `RegExp`/`multiLine` helpers below, whose `$` already
/// treats `\r\n` as a line terminator) can match regardless of the
/// working tree's line-ending style, then converts back to the file's
/// original line ending on [save] so the edit doesn't flip the rest of
/// the file's endings.
class _RawFile {
  final File file;
  final bool _wasCrlf;
  String content;

  _RawFile(this.file)
    : _wasCrlf = file.readAsStringSync().contains('\r\n'),
      content = file.readAsStringSync().replaceAll('\r\n', '\n');

  void save() {
    file.writeAsStringSync(_wasCrlf ? content.replaceAll('\n', '\r\n') : content);
  }
}

// ------------------------------------------------------------------
// 🧩 HELPER FUNCTIONS
// ------------------------------------------------------------------

/// Inserts [insertion] immediately before the line containing
/// `// {marker}_END` in [content]. Returns `null` (instead of guessing via
/// brace-counting or substring search) if that marker isn't present, so
/// callers can fail loudly with instructions rather than silently
/// corrupting a file whose shape doesn't match what was assumed.
String? _insertBeforeMarker(String content, String marker, String insertion) {
  final endMarkerLine = RegExp(
    '^[ \\t]*// ${RegExp.escape(marker)}_END[ \\t]*\$',
    multiLine: true,
  ).firstMatch(content);
  if (endMarkerLine == null) return null;

  final lineStart = content.lastIndexOf('\n', endMarkerLine.start) + 1;
  return content.substring(0, lineStart) +
      insertion +
      content.substring(lineStart);
}

/// Inserts [importLine] right before the `// GENERATED_IMPORTS_END` marker
/// in [content], unless it's already present. Returns `null` if that
/// marker isn't found.
String? _insertImportIfMissing(String content, String importLine) {
  if (content.contains(importLine)) return content;
  return _insertBeforeMarker(content, 'GENERATED_IMPORTS', '$importLine\n');
}

/// Runs `dart format` on every file/directory this hook touched or
/// generated, so brick-generated code doesn't drift from the project's
/// formatting standard over time.
Future<void> _formatPaths(List<String> paths, Logger logger) async {
  if (paths.isEmpty) return;

  final result = await Process.run('dart', [
    'format',
    ...paths,
  ], runInShell: true);

  if (result.exitCode == 0) {
    logger.success('🎨 Formatted generated/updated files');
  } else {
    logger.warn('⚠️  dart format failed: ${result.stderr}');
  }
}
