// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_generator brick
// To regenerate, run: mason make asset_generator

/// Contains all icon asset paths used in the application.
/// 
/// Usage:
/// ```dart
/// Image.asset(AppIcons.homeIcon)
/// ```
class AppIcons {
  AppIcons._();
{{#icons}}
  

  static const String {{{const_name}}} = '{{{asset_path}}}';
{{/icons}}
{{^icons}}
  
  // No icons found in assets/icons folder
{{/icons}}
}