// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_generator brick
// To regenerate, run: mason make asset_generator

/// Contains all image asset paths used in the application.
/// 
/// Usage:
/// ```dart
/// Image.asset(AppImages.appLogo)
/// ```
class AppImages {
  AppImages._();
{{#images}}
  
  static const String {{{const_name}}} = '{{{asset_path}}}';
{{/images}}
{{^images}}
  
  // No images found in assets/images folder
{{/images}}
}