import 'dart:io';
import 'package:mason/mason.dart';

// The feature's own files (page, viewmodel, datasource, usecase,
// repository, models, exports barrel...) are generated by Mason itself
// from __brick__/features/{{fileName}}/..., using the fileName/className/
// camelName vars computed in pre_gen.dart. This hook only handles wiring
// the freshly-generated feature into files that already existed before
// this run — route_names.dart, route_paths.dart, app_router.dart, and
// injection_container.dart — which Mason's template step can't touch
// since they aren't part of this brick's own output tree.
//
// All insertions below use `// GENERATED_..._START` / `_END` marker
// comments (already present in the shipped template's route/DI files) as
// stable anchors, instead of brace-counting or substring-searching for
// things like `routes: [` — that broke the moment those files grew route
// guards, nested routes, or a stray brace inside a string literal.
Future<void> run(HookContext context) async {
  final logger = context.logger;

  final fileName = context.vars['fileName'] as String;
  final className = context.vars['className'] as String;
  final camelName = context.vars['camelName'] as String;

  final libDir = Directory('${Directory.current.path}/lib');
  final touchedFiles = <File>[];

  touchedFiles.addAll(_updateRoutes(libDir, className, fileName, logger));
  touchedFiles.addAll(
    _updateDependencyInjection(libDir, className, fileName, camelName, logger),
  );

  // Also format the feature Mason just generated from __brick__ — Mason
  // doesn't run a formatter itself, so left alone this drifts from the
  // project's style the same way the manual file-surgery above used to.
  final featureDir = Directory('${libDir.path}/features/$fileName');
  await _formatPaths([...touchedFiles.map((f) => f.path), if (featureDir.existsSync()) featureDir.path], logger);

  logger.success('\n✅ $className feature wired into routes and DI!');
  logger.info(
    '💡 The generated Params/Response models use freezed — run '
    "'dart run build_runner build --delete-conflicting-outputs' before "
    'building the app.',
  );
}

// ------------------------------------------------------------------
// 🧩 UPDATE ROUTES AUTOMATICALLY
// ------------------------------------------------------------------
List<File> _updateRoutes(
  Directory libDir,
  String className,
  String fileName,
  Logger logger,
) {
  final routesDir = Directory('${libDir.path}/routes');
  final touched = <File>[];

  // ✅ 1. Update route_names.dart
  final namesFile = File('${routesDir.path}/route_names.dart');
  if (namesFile.existsSync()) {
    String content = namesFile.readAsStringSync();

    if (!content.contains('static const String $fileName')) {
      final updated = _insertBeforeMarker(
        content,
        'GENERATED_ROUTE_NAMES',
        '  static const String $fileName = "$fileName";\n',
      );
      if (updated != null) {
        namesFile.writeAsStringSync(updated);
        touched.add(namesFile);
        logger.success('🧭 Updated: lib/routes/route_names.dart');
      } else {
        logger.err(
          '❌ lib/routes/route_names.dart is missing the '
          '"// GENERATED_ROUTE_NAMES_END" marker — add it inside the '
          'RouteNames class and re-run.',
        );
      }
    } else {
      logger.warn('⚠️  Route name "$fileName" already exists');
    }
  }

  // ✅ 2. Update route_paths.dart
  final pathsFile = File('${routesDir.path}/route_paths.dart');
  if (pathsFile.existsSync()) {
    String content = pathsFile.readAsStringSync();

    if (!content.contains('static const String $fileName')) {
      final updated = _insertBeforeMarker(
        content,
        'GENERATED_ROUTE_PATHS',
        '  static const String $fileName = "/$fileName";\n',
      );
      if (updated != null) {
        pathsFile.writeAsStringSync(updated);
        touched.add(pathsFile);
        logger.success('🧭 Updated: lib/routes/route_paths.dart');
      } else {
        logger.err(
          '❌ lib/routes/route_paths.dart is missing the '
          '"// GENERATED_ROUTE_PATHS_END" marker — add it inside the '
          'RoutePaths class and re-run.',
        );
      }
    } else {
      logger.warn('⚠️  Route path "/$fileName" already exists');
    }
  }

  // ✅ 3. Update app_router.dart
  final routerFile = File('${routesDir.path}/app_router.dart');
  if (routerFile.existsSync()) {
    String content = routerFile.readAsStringSync();

    if (!content.contains('${className}Page()')) {
      // Make sure the new feature's page type is actually importable.
      // One fewer "../" than the DI file's version below: app_router.dart
      // lives at lib/routes/, a sibling of core/, not nested inside it.
      final withImport = _insertImportIfMissing(
        content,
        "import '../features/$fileName/${fileName}_exports.dart';",
      );
      if (withImport == null) {
        logger.err(
          '❌ lib/routes/app_router.dart is missing the '
          '"// GENERATED_IMPORTS_END" marker — add it below the existing '
          'imports and re-run.',
        );
      } else {
        content = withImport;

        final newRoute =
            '''
      GoRoute(
        path: RoutePaths.$fileName,
        name: RouteNames.$fileName,
        builder: (context, state) => const ${className}Page(),
      ),''';

        final updated = _insertBeforeMarker(
          content,
          'GENERATED_ROUTES',
          '$newRoute\n',
        );
        if (updated != null) {
          routerFile.writeAsStringSync(updated);
          touched.add(routerFile);
          logger.success('🧭 Updated: lib/routes/app_router.dart');
        } else {
          logger.err(
            '❌ lib/routes/app_router.dart is missing the '
            '"// GENERATED_ROUTES_END" marker — add it right before the '
            'closing "]," of AppRoutes.router\'s routes list and re-run.',
          );
        }
      }
    } else {
      logger.warn('⚠️  Route for ${className}Page already exists');
    }
  }

  return touched;
}

// ------------------------------------------------------------------
// 🧩 UPDATE DEPENDENCY INJECTION AUTOMATICALLY
// ------------------------------------------------------------------
List<File> _updateDependencyInjection(
  Directory libDir,
  String className,
  String fileName,
  String camelName,
  Logger logger,
) {
  final diFile = File('${libDir.path}/core/di/injection_container.dart');

  if (!diFile.existsSync()) {
    logger.err('❌ injection_container.dart not found');
    return const [];
  }

  String content = diFile.readAsStringSync();

  // Check if dependencies already exist
  if (content.contains('${camelName}Dependencies')) {
    logger.warn('⚠️  Dependencies for $fileName already exist');
    return const [];
  }

  // Make sure the new feature's DataSource/Repository/Usecase/ViewModel
  // types are actually importable before we reference them below.
  final withImport = _insertImportIfMissing(
    content,
    "import '../../features/$fileName/${fileName}_exports.dart';",
  );
  if (withImport == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_IMPORTS_END" marker — add it below the existing '
      'imports and re-run.',
    );
    return const [];
  }
  content = withImport;

  // ✅ 1. Add the dependency function, right before GENERATED_DEPENDENCIES_END
  final newDependencyFunction =
      '''
/// $className Feature Dependencies
Future<void> ${camelName}Dependencies() async {
  // DataSource
  sl.registerLazySingleton<IRemote${className}DataSource>(
    () => Remote${className}DataSourceImpl(dioHelper: sl()),
  );

  // Repository
  sl.registerLazySingleton<I${className}Repository>(
    () => ${className}RepositoryImpl(dataSource: sl()),
  );

  // UseCase
  sl.registerLazySingleton<${className}Usecase>(
    () => ${className}Usecase(repository: sl()),
  );

  // ViewModel
  sl.registerFactory<${className}ViewModel>(
    () => ${className}ViewModel(${camelName}Usecase: sl()),
  );
}

''';

  final withDependencyFunction = _insertBeforeMarker(
    content,
    'GENERATED_DEPENDENCIES',
    newDependencyFunction,
  );
  if (withDependencyFunction == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_DEPENDENCIES_END" marker — add it at the end of the '
      'file and re-run.',
    );
    return const [];
  }
  content = withDependencyFunction;

  // ✅ 2. Add the function call, right before GENERATED_SETUP_CALLS_END
  // (inside setupLocator()).
  final withSetupCall = _insertBeforeMarker(
    content,
    'GENERATED_SETUP_CALLS',
    '  await ${camelName}Dependencies();\n',
  );
  if (withSetupCall == null) {
    logger.err(
      '❌ lib/core/di/injection_container.dart is missing the '
      '"// GENERATED_SETUP_CALLS_END" marker — add it at the end of '
      'setupLocator() and re-run.',
    );
    return const [];
  }
  content = withSetupCall;

  diFile.writeAsStringSync(content);
  logger.success('🧱 Updated: lib/core/di/injection_container.dart');
  return [diFile];
}

// ------------------------------------------------------------------
// 🧩 HELPER FUNCTIONS
// ------------------------------------------------------------------

/// Inserts [insertion] immediately before the line containing
/// `// {marker}_END` in [content]. Returns `null` (instead of guessing via
/// brace-counting or substring search) if that marker isn't present, so
/// callers can fail loudly with instructions rather than silently
/// corrupting a file whose shape doesn't match what was assumed.
String? _insertBeforeMarker(String content, String marker, String insertion) {
  final endMarkerLine = RegExp(
    '^[ \\t]*// ${RegExp.escape(marker)}_END[ \\t]*\$',
    multiLine: true,
  ).firstMatch(content);
  if (endMarkerLine == null) return null;

  final lineStart = content.lastIndexOf('\n', endMarkerLine.start) + 1;
  return content.substring(0, lineStart) +
      insertion +
      content.substring(lineStart);
}

/// Inserts [importLine] right before the `// GENERATED_IMPORTS_END` marker
/// in [content], unless it's already present. Returns `null` if that
/// marker isn't found.
String? _insertImportIfMissing(String content, String importLine) {
  if (content.contains(importLine)) return content;
  return _insertBeforeMarker(content, 'GENERATED_IMPORTS', '$importLine\n');
}

/// Runs `dart format` on every file/directory this hook touched or
/// generated, so brick-generated code doesn't drift from the project's
/// formatting standard over time.
Future<void> _formatPaths(List<String> paths, Logger logger) async {
  if (paths.isEmpty) return;

  final result = await Process.run('dart', [
    'format',
    ...paths,
  ], runInShell: true);

  if (result.exitCode == 0) {
    logger.success('🎨 Formatted generated/updated files');
  } else {
    logger.warn('⚠️  dart format failed: ${result.stderr}');
  }
}
