// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_generator brick
// To regenerate, run: mason make asset_generator

/// Contains all image asset paths used in the application.
/// 
/// Usage:
/// ```dart
/// Image.asset(AppImages.appLogo)
/// ```
class AppImages {
  AppImages._();

  
  static const String image = 'assets/images/image.png';


}