// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_generator brick
// To regenerate, run: mason make asset_generator

/// Contains all icon asset paths used in the application.
/// 
/// Usage:
/// ```dart
/// Image.asset(AppIcons.homeIcon)
/// ```
class AppIcons {
  AppIcons._();

  

  static const String icon = 'assets/icons/icon.png';

  

  static const String logo = 'assets/icons/logo.png';


}