// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_generator brick
// To regenerate, run: mason make asset_generator

/// Contains all icon asset paths used in the application.
///
/// Usage:
/// ```dart
/// Image.asset(AppIcons.homeIcon)
/// ```
class AppIcons {
  AppIcons._();

  static const String apple = 'assets/icons/apple.png';

  static const String bank = 'assets/icons/bank.png';

  static const String businessCard = 'assets/icons/business_card.png';

  static const String camera = 'assets/icons/camera.png';

  static const String contracts = 'assets/icons/contracts.jpg';

  static const String drive = 'assets/icons/drive.png';

  static const String drivingLicense = 'assets/icons/driving_license.webp';

  static const String exportPagesAsPdf =
      'assets/icons/export_pages_as_pdf.png';

  static const String filesIos = 'assets/icons/files-ios.png';

  static const String galleryAndroid = 'assets/icons/gallery-android.png';

  static const String galleryIos = 'assets/icons/gallery-ios.png';

  static const String gmail = 'assets/icons/gmail.png';

  static const String google = 'assets/icons/google.webp';

  static const String idcard = 'assets/icons/idcard.jpg';

  static const String insurance = 'assets/icons/insurance.webp';

  static const String instagram = 'assets/icons/instagram.png';

  static const String medical = 'assets/icons/medical.png';

  static const String messenger = 'assets/icons/messenger.png';

  static const String passports = 'assets/icons/passports.webp';

  static const String power = 'assets/icons/power.png';

  static const String products = 'assets/icons/products.png';

  static const String saveToGallery = 'assets/icons/save_to_gallery.png';

  static const String shareAsImages = 'assets/icons/share_as_images.png';

  static const String shareAsPdf = 'assets/icons/share_as_pdf.png';

  static const String tickets = 'assets/icons/tickets.png';

  static const String whatsapp = 'assets/icons/whatsapp.png';
}
